# borrowed with <3 from https://github.com/serilog/serilog/blob/dev/appveyor.yml
version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Concept.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: qmdWddVntwIfcKoTljpVw6COEdvf0Sb4UIQJM4EkCp487IQRwwhqSue+lQIajUra
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: 1yhor7j2L0Qd1mK5l3JSoGAVr1zCDjGj2vhQkTQCMm3Q1MzFpAQqiuxLzCjUKyS9
  artifact: /Concept.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master